import Footer from "@/components/(website)/Footer";
import Header from "@/components/(website)/Header";
import type { Metadata } from "next";
import { Cinzel, Inter } from "next/font/google";
import "./globals.css";
import NavBottom from "@/components/(website)/NavBottom";
const inter = Inter({ subsets: ["latin"] });
const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen justify-between w-full flex flex-col ">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
